# Starter pipeline
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
  #  linux:
 #     imageName: 'ubuntu-16.04'
  #  mac:
   #   imageName: 'macos-10.13'
    windows:
      imageName: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
